apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "glassflow-etl.fullname" . }}-api-rolebinding
  labels:
  {{- include "glassflow-etl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ .Release.Name }}-pipeline-editor-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "glassflow-etl.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
