{{- if or .Values.global.observability.metrics.enabled .Values.global.observability.logs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-otel-collector
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-otel-collector
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-otel-collector
    spec:
      containers:
      - name: {{ .Release.Name }}-otel-collector
        image: otel/opentelemetry-collector-contrib:0.108.0
        command:
          - "/otelcol-contrib"
          - "--config=/etc/otel-collector-config.yaml"
        resources:
          {{- toYaml (default (dict "requests" (dict "cpu" "100m" "memory" "128Mi") "limits" (dict "cpu" "500m" "memory" "512Mi")) .Values.global.observability.otelCollector.resources) | nindent 10 }}
        ports:
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
{{- if and .Values.global.observability.metrics.enabled (hasKey (default dict .Values.global.observability.metrics.exporter) "prometheus") }}
        {{- $prometheusPort := .Values.global.observability.metrics.exporter.prometheus.endpoint | splitList ":" | last | int }}
        - containerPort: {{ $prometheusPort }}
          name: prometheus
{{- end }}
        - containerPort: 13133
          name: health-check
        volumeMounts:
        - name: config
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-collector-config.yaml
        livenessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-otel-collector-config
{{- end }}
