# =============================================================================
# INGRESS CONFIGURATION WITH TLS
# =============================================================================
# Ingress configuration for external access to the application with TLS support
ingress:
  # Enable or disable ingress
  # Set to true to expose the application externally
  enabled: true
  
  # Ingress class name (required for Kubernetes 1.18+)
  # Example: "nginx", "traefik", "istio"
  ingressClassName: "nginx"

  # Annotations for the ingress resource
  # Cert-manager annotations for automatic TLS certificate management
  annotations:
    # Cert-manager cluster issuer for Let's Encrypt
    cert-manager.io/cluster-issuer: "letsencrypt-prod"    
    # Nginx ingress controller annotations
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"        

  hosts: 
  - host: "glassflow.example.com"
    paths:
    - path: "/"
      pathType: Prefix
      serviceName: "glassflow-ui"
      servicePort: 8080
    - path: "/api/v1"
      pathType: Prefix
      serviceName: "glassflow-api"
      servicePort: 8081

  # TLS configuration for HTTPS with Let's Encrypt
  # Cert-manager will automatically create and manage the TLS secret
  tls:
    - hosts:
        - "glassflow.example.com"
      secretName: "glassflow-tls-secret"
