# Example values to show how to configure ingress

# =============================================================================
# INGRESS CONFIGURATION
# =============================================================================
# Ingress configuration for external access to the application
ingress:
  # Enable or disable ingress
  # Set to true to expose the application externally
  enabled: true  
  # Ingress class name (required for Kubernetes 1.18+)
  # Example: "nginx", "traefik", "istio"
  ingressClassName: "nginx"

  # Annotations for the ingress resource
  # Useful for SSL termination, rate limiting, etc.
  annotations: {}

  # Host configurations for the ingress  
  hosts: 
  - host: "glassflow.example.com"
    paths:
    - path: "/"
      pathType: Prefix
      serviceName: "glassflow-ui"
      servicePort: 8080
    - path: "/api/v1"
      pathType: Prefix
      serviceName: "glassflow-api"
      servicePort: 8081

  # TLS configuration for HTTPS
  # Example:
  # - hosts:
  #     - "glassflow.example.com"
  #   secretName: "glassflow-tls-secret"
  tls: []